// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc364.TutorialJava;

import org.usfirst.frc364.TutorialJava.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.buttons.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);
    
    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.
    
    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:
    
    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());
    
    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());
    
    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());

    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton shiftHigh;
    public JoystickButton shiftLow;
    public Joystick leftJoystick;
    public Joystick rightJoystick;
    public JoystickButton dropSetpoint;
    public JoystickButton transportSetpoint;
    public JoystickButton liftSetpoint;
    public JoystickButton openArms;
    public JoystickButton closeArms;
    public JoystickButton pickupTote;
    public Joystick controller;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        controller = new Joystick(2);
        
        pickupTote = new JoystickButton(controller, 3);
        pickupTote.whenPressed(new liftCommand());
        closeArms = new JoystickButton(controller, 7);
        closeArms.whenPressed(new armCommand());
        openArms = new JoystickButton(controller, 8);
        openArms.whenPressed(new armCommand());
        liftSetpoint = new JoystickButton(controller, 6);
        liftSetpoint.whenPressed(new liftCommand());
        transportSetpoint = new JoystickButton(controller, 1);
        transportSetpoint.whenPressed(new liftCommand());
        dropSetpoint = new JoystickButton(controller, 2);
        dropSetpoint.whenPressed(new liftCommand());
        rightJoystick = new Joystick(1);
        
        leftJoystick = new Joystick(0);
        
        shiftLow = new JoystickButton(leftJoystick, 2);
        shiftLow.whenPressed(new shiftCommand());
        shiftHigh = new JoystickButton(leftJoystick, 1);
        shiftHigh.whenPressed(new shiftCommand());

	    
        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());

        SmartDashboard.putData("driveCommand", new driveCommand());

        SmartDashboard.putData("armCommand", new armCommand());

        SmartDashboard.putData("shiftCommand", new shiftCommand());

        SmartDashboard.putData("liftCommand", new liftCommand());

        SmartDashboard.putData("intakeCommand", new intakeCommand());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getleftJoystick() {
        return leftJoystick;
    }

    public Joystick getrightJoystick() {
        return rightJoystick;
    }

    public Joystick getcontroller() {
        return controller;
    }

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

